---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
netPropPath <- '/home/gummi/netprop'
library(igraph)
library(dplyr)
source(paste0(netPropPath, '/Code/NetPropFuncs.R'))
if(file.exists(paste0(netPropPath,"/data/intGraph.rdata"))){
    load(paste0(netPropPath,"/data/intGraph.rdata"))
} 

```

```{r }
seedVector <- rep(1, vcount(intGraph))

ECvec <- igraph::page_rank(intGraph, directed = FALSE, damping = 1, personalized = seedVector,algo="arpack")

assocDataBySourceDirectFiltered <- read.csv(paste0(netPropPath,"/data/associationByDatasourceDirectFiltered.csv"), stringsAsFactors = FALSE)
assocDataBySourceDirIndiMergedFiltered <- read.csv(paste0(netPropPath,"/data/associationByDatasourceDirIndirMergedFiltered.csv"), stringsAsFactors = FALSE)

seedVecsDirect <- runNetProp(network = intGraph,
                    assocData = assocDataBySourceDirectFiltered,
                    cutoff = c("value" = 0.1, "number" = 1),
                    binarize = TRUE,
                    damping = 0.85,
                    NormFunc = NULL,
                    settingsForNormFunc = NULL,
                    returnSeedVec = TRUE)

nSeedsDir <- rowSums(seedVecsDirect)

# Remove any zeros

nSeedsDir <- nSeedsDir[nSeedsDir != 0]

seedVecsIndir <- runNetProp(network = intGraph,
                    assocData = assocDataBySourceDirIndiMergedFiltered,
                    cutoff = c("value" = 0.1, "number" = 1),
                    binarize = TRUE,
                    damping = 0.85,
                    NormFunc = NULL,
                    settingsForNormFunc = NULL,
                    returnSeedVec = TRUE)

nSeedsIndir <- rowSums(seedVecsIndir)

# Remove any zeros

nSeedsIndir <- nSeedsIndir[nSeedsIndir != 0]

summary(nSeedsDir)
summary(nSeedsIndir)



```

```{r }

# Get the indices of the genes that appear in the seed vectors
seedInds <- which(colSums(seedVecsDirect) != 0)


# Compute average network propagation vector by using random seeds and compare the distance to the EC vector for every iteration 
avgVec <- rep(1/vcount(intGraph), vcount(intGraph))

i <- 1
while(i < 10000){
    seedVector <- rep(0, vcount(intGraph))
    seedVector[sample(seedInds,sample(nSeedsDir,1))] <- 1	
    
    tempVec <- igraph::page_rank(intGraph,directed = FALSE, personalized = seedVector)$vector 
    
    #Save the old
    avgVecOld <- avgVec

    # Update the average vector
    avgVec <- avgVec + (tempVec - avgVec)/i

    # Compute the distance between the EC vector and the average vector
    if(i %% 100 == 0){
        distance <- as.numeric(dist(rbind(avgVec, ECvec$vector), method = "manhattan"))
        delta <- as.numeric(dist(rbind(avgVec, avgVecOld), method = "manhattan"))
        print(paste0("Iteration: ", i, " Distance: ", distance, " Delta: ", delta))
    }
    i <- i + 1

}

# Make a dataframe with the gene names and the average vector
avgVecDF <- data.frame(gene = V(intGraph)$name, avgVec = avgVec)

# Save the average vector
write.csv(avgVecDF, paste0(netPropPath,"/data/averageVecDirect.csv"), row.names = FALSE)

```


```{r }
# Do the same thing for the indirect associations
# Get the indices of the genes that appear in the seed vectors
seedInds <- which(colSums(seedVecsIndir) != 0)

# Compute average network propagation vector by using random seeds and compare the distance to the EC vector for every iteration 
avgVec <- rep(1/vcount(intGraph), vcount(intGraph))

i <- 1
while(i < 10000){
    seedVector <- rep(0, vcount(intGraph))
    seedVector[sample(seedInds,sample(nSeedsIndir,1))] <- 1	
    
    tempVec <- igraph::page_rank(intGraph,directed = FALSE, personalized = seedVector)$vector 
    
    #Save the old
    avgVecOld <- avgVec

    # Update the average vector
    avgVec <- avgVec + (tempVec - avgVec)/i

    # Compute the distance between the EC vector and the average vector
    if(i %% 100 == 0){
        distance <- as.numeric(dist(rbind(avgVec, ECvec$vector), method = "manhattan"))
        delta <- as.numeric(dist(rbind(avgVec, avgVecOld), method = "manhattan"))
        print(paste0("Iteration: ", i, " Distance: ", distance, " Delta: ", delta))
    }
    i <- i + 1

}

# Make a dataframe with the gene names and the average vector
avgVecDF <- data.frame(gene = V(intGraph)$name, avgVec = avgVec)

# Save the average vector
write.csv(avgVecDF, paste0(netPropPath,"/data/averageVecInDirect.csv"), row.names = FALSE)

```



```{r }
# Compare the two average vectors
avgVecDirect <- read.csv(paste0(netPropPath,"/data/averageVecDirect.csv"), stringsAsFactors = FALSE)
avgVecIndirect <- read.csv(paste0(netPropPath,"/data/averageVecInDirect.csv"), stringsAsFactors = FALSE)

# Compute the distance between the two average vectors
distance <- as.numeric(dist(rbind(avgVecDirect$avgVec, avgVecIndirect$avgVec, ECvec$vector), method = "manhattan"))

# Create a vector that is the average of the two vectors and compare the distance to the EC vector
avgVecCombined <- (avgVecDirect$avgVec + avgVecIndirect$avgVec)/2

distanceCombined <- as.numeric(dist(rbind(avgVecCombined, ECvec$vector), method = "manhattan"))

sum(avgVecCombined)

# Save the combined vector
write.csv(data.frame(gene = V(intGraph)$name, avgVec = avgVecCombined), paste0(netPropPath,"/data/averageVecCombined.csv"), row.names = FALSE)
```

```{r }

seedVec <- rep(1/vcount(intGraph), vcount(intGraph))

nIter <- 100

for(i in seq(0.01,0.99,0.01)){
    
    res <- igraph::page_rank(intGraph, damping = i,directed = FALSE, personalized = seedVector)$vector 

    # Compute the distance between the EC vector and the average vector
    distanceVec[i*100] <- as.numeric(dist(rbind(res, ECvec$vector), method = "manhattan"))
    print(distanceVec[i*100])

}


```