---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
netPropPath <- "/home/gummi/netprop"
load("/home/gummi/netprop/masterResDamping.rdata")
library(ggplot2)
library(dplyr)
source(paste0(netPropPath, '/Code/NetPropFuncs.R'))
diseaseMapping <- read.csv("/home/gummi/netprop/data/phenotypeMapping.csv")


knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE) 
```

## AREA UNDER THE COSINE CURVE
```{r }

dampingVec <- as.character(seq(0.5, 0.95, 0.05))

# Gather all the distance values in a single matrix by using as.vector on the distance objects

allDistancesL <- lapply(dampingVec, function(damping){
  as.vector(masterRes[["AllTraitsOverallScores"]][["noNorm"]][[damping]][["cosine"]][["Rawdist"]])
})

allDistances <- do.call(cbind, allDistancesL)

#allDistances <- 1 - allDistances

# Calculate the area under the curve for each damping value using the DescTools::AUC(

aucVec <- sapply(1:nrow(allDistances), function(i){

  DescTools::AUC(y = allDistances[i,],x = seq(0.5,0.95,0.05))/0.45

})

str(aucVec)

class(aucVec) <- "dist"
attr(aucVec, "Size") <- attr(masterRes[["AllTraitsOverallScores"]][["noNorm"]][[1]][["cosine"]][["Rawdist"]],"Size")
attr(aucVec, "Diag") <- attr(masterRes[["AllTraitsOverallScores"]][["noNorm"]][[1]][["cosine"]][["Rawdist"]],"Diag")
attr(aucVec, "Upper") <- attr(masterRes[["AllTraitsOverallScores"]][["noNorm"]][[1]][["cosine"]][["Rawdist"]],"Upper")
attr(aucVec, "Labels") <- attr(masterRes[["AllTraitsOverallScores"]][["noNorm"]][[1]][["cosine"]][["Rawdist"]],"Labels")
idToName <- setNames(as.character(diseaseMapping$name), as.character(diseaseMapping$id))



distdex<-function(i,j,n) {
    n*(i-1) - i*(i-1)/2 + j-i
}

rowcol<-function(ix,n) { #given index, return row and column
    nr=ceiling(n-(1+sqrt(1+4*(n^2-n-2*ix)))/2)
    nc=n-(2*n-nr+1)*nr/2+ix+nr
    cbind(nr,nc)
}

# get the indexs of the top 1
#aucVec <- 1 - aucVec 

```


```{r }
randTraitPair <- sample(1:attr(aucVec,"Size"), 2)

# Pick a random pair with high auc value
while(aucVec[distdex(randTraitPair[1], randTraitPair[2], attr(aucVec,"Size"))] < 0.3){
  randTraitPair <- sample(1:attr(aucVec,"Size"), 2)
}




index <- distdex(randTraitPair[1], randTraitPair[2], attr(aucVec,"Size"))

plot(y = 1 - allDistances[index,],x = seq(0.5, 0.95, 0.05),
        type = "l",
        xlab = "Damping",
        ylab = "Distance",
        ylim =c(0,1),
        main = paste0("AUC: ", round(aucVec[index],2),
        "  \n  ", idToName[attr(aucVec,"Labels")[randTraitPair[1]]], " \n ", idToName[attr(aucVec,"Labels")[randTraitPair[2]]]))
        

```

```{r }

source(paste0(netPropPath, '/Code/NetPropFuncs.R'))

relationships <- read.csv(paste0(netPropPath,"/relationshipsWithNames.csv"), stringsAsFactors = FALSE) %>%
                 filter(term1 %in% attr(aucVec,"Labels") & term2 %in% attr(aucVec,"Labels")) %>%
                    select(term1, term2) %>%
                    as.matrix()


distAnalyzeRes <- analyzeDistance(allMetric = aucVec,
                            diseasePairs = relationships,
                            randomSetSize = 8,
                            preferredClusterNumber = round(sqrt(attr(aucVec,"Size"))*1.5),
                            kparam = round(sqrt(attr(aucVec,"Size"))),
                            traitIDs = attr(aucVec,"Labels"),
                            diseasesDataFrame = diseaseMapping) 



```


```{r }
plots <- generatePlotsFromDistCompareResults(distAnalyzeRes, diseaseMapping = diseaseMapping, densityOnly = FALSE)

```

```{r }

plots[["DensityPlot"]]    
```

```{r }
plots <- generatePlotsFromDistCompareResults(masterRes[["AllTraitsOverallScores"]][["ECnormLog"]][["0.95"]][["cosine"]], diseaseMapping = diseaseMapping, densityOnly = FALSE)
plots[["DensityPlot"]]    

```



```{r }
dat1 <- runif(10)
dat1[1] <- 0
dat1 <- dat1/sum(dat1)

dat2 <- runif(10)
dat2[2] <- 0
dat2 <- dat2/sum(dat2)

dat3 <- runif(10)
dat3[3] <- 0
dat3 <- dat3/sum(dat3)

philentropy::JSD(rbind(dat1, dat2, dat3))




```
